export const AuthErrors = {
  USER_NOT_FOUND: 'User not found',
  USER_ALREADY_EXISTS: 'User already exists',
  INVALID_CREDENTIALS: 'Invalid credentials',
  INVALID_TOKEN: 'Invalid token',
  TOKEN_EXPIRED: 'Token expired',
  REFRESH_TOKEN_NOT_FOUND: 'Refresh token not found',
  REFRESH_TOKEN_EXPIRED: 'Refresh token expired',
  EMAIL_ALREADY_VERIFIED: 'Email already verified',
  EMAIL_NOT_VERIFIED: 'Email not verified',
  EMAIL_VERIFICATION_FAILED: 'Email verification failed',
  PASSWORD_RESET_FAILED: 'Password reset failed',
  PASSWORD_RESET_TOKEN_EXPIRED: 'Password reset token expired',
  PASSWORD_RESET_TOKEN_INVALID: 'Password reset token invalid',
  UNAUTHORIZED: 'Unauthorized',
  FORBIDDEN: 'Forbidden',
};
